databases:
  - name: postgres
    ipAllowList: []
    databaseName: comics_list_api_production
    user: comics_list_api
    plan: free

services:
  - type: web
    name: comics_list_api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
