databases:
  - name: comics_list_api
    databaseName: comics_list_api_production
    user: comics_list_api

services:
  - type: web
    name: comics_list_api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: comics_list_api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
